# Generated by Django 3.2.4 on 2021-10-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20211008_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoints', models.ManyToManyField(related_name='sampleinfo_datapoint', to='ui.SampleDatapoint')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='sampleinfo', to='ui.sample')),
                ('samplespec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sampleinfo_patientspec', to='ui.samplespecification')),
            ],
            options={
                'unique_together': {('sample', 'samplespec')},
            },
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoints', models.ManyToManyField(related_name='patientinfo_datapoint', to='ui.PatientDatapoint')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='patientinfo', to='ui.patient')),
                ('patientspec', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patientinfo_patientspec', to='ui.patientspecification')),
            ],
            options={
                'unique_together': {('patient', 'patientspec')},
            },
        ),
    ]
