# Generated by Django 3.2.4 on 2021-10-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_patientinfo_sampleinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='projectid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='patientinfo', to='ui.projectid'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='patientinfo',
            unique_together={('projectid', 'patientspec')},
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='patient',
        ),
    ]
