# Generated by Django 3.2.4 on 2021-10-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20211008_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientspecification',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientspec', to='ui.project'),
        ),
        migrations.AlterField(
            model_name='samplespecification',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='samplespec', to='ui.project'),
        ),
    ]
