# Generated by Django 3.2.4 on 2021-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20211010_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='visit',
            field=models.IntegerField(default=1),
        ),
    ]
