# Generated by Django 3.2.4 on 2021-12-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_sample_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatapointsRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoints', models.ManyToManyField(related_name='datapointsrow_datapoint', to='ui.Datapoint')),
            ],
        ),
        migrations.AddField(
            model_name='geneanalysis',
            name='datapointsrows',
            field=models.ManyToManyField(related_name='geneanalysis_datapointsrows', to='ui.DatapointsRow'),
        ),
    ]
