# Generated by Django 3.2.4 on 2022-03-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20211216_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gene',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='projectid',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projectid_patient', to='ui.patient'),
        ),
    ]
