# Generated by Django 3.2.4 on 2022-03-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20220301_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdpts',
            name='patientspec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='patientdpts_patientspec', to='ui.patientspecification'),
        ),
        migrations.AlterField(
            model_name='patientspecification',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='patientspec', to='ui.project'),
        ),
    ]
