# Generated by Django 3.2.4 on 2022-03-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20220301_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='projectid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientinfo', to='ui.projectid'),
        ),
    ]
