# Generated by Django 3.2.4 on 2022-03-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_alter_patientinfo_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientspecification',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientspec', to='ui.project'),
        ),
        migrations.AlterField(
            model_name='sampleinfo',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sampleinfo', to='ui.sample'),
        ),
        migrations.AlterField(
            model_name='samplespecification',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='samplespec', to='ui.project'),
        ),
    ]
