# Generated by Django 3.2.4 on 2022-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_auto_20220301_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdpts',
            name='priority',
            field=models.IntegerField(default='999'),
        ),
    ]
