# Generated by Django 3.2.4 on 2022-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0016_patientdpts_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdpts',
            options={'ordering': ('priority',)},
        ),
        migrations.AlterModelOptions(
            name='sampledpts',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='sampledpts',
            name='priority',
            field=models.IntegerField(default='999'),
        ),
    ]
