# Generated by Django 3.2.4 on 2022-03-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0018_auto_20220309_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdatapoint',
            options={'ordering': ('patientdpts__priority',)},
        ),
    ]
