# Generated by Django 3.2.4 on 2022-03-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_alter_patientdatapoint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chipsetdatapoint',
            options={'ordering': ('confdpts__priority',)},
        ),
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ('specdpts__priority',)},
        ),
        migrations.AlterModelOptions(
            name='sampledatapoint',
            options={'ordering': ('sampledpts__priority',)},
        ),
    ]
