# Generated by Django 3.2.4 on 2022-07-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0021_alter_sample_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chipsetanalysis',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='geneanalysis',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='projectid',
            options={'ordering': ('-pk',)},
        ),
    ]
