# Generated by Django 3.2.4 on 2022-07-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0022_auto_20220712_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chipsetdatapoint',
            options={'ordering': ('confdpts__priority', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='confdpts',
            options={'ordering': ('priority', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ('specdpts__priority', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='gene',
            options={'ordering': ('name', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='patientdatapoint',
            options={'ordering': ('patientdpts__priority', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='patientdpts',
            options={'ordering': ('priority', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='sampledatapoint',
            options={'ordering': ('sampledpts__priority', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='sampledpts',
            options={'ordering': ('priority', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='specdpts',
            options={'ordering': ('priority', '-pk')},
        ),
    ]
