# Generated by Django 3.2.4 on 2022-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0023_auto_20220719_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipsetDatapointsRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoints', models.ManyToManyField(related_name='chipsetdatapointsrow_datapoint', to='ui.Datapoint')),
            ],
        ),
        migrations.AddField(
            model_name='chipsetanalysis',
            name='datapointsrows',
            field=models.ManyToManyField(related_name='chipsetanalysis_datapointsrows', to='ui.ChipsetDatapointsRow'),
        ),
    ]
