# Generated by Django 3.2.4 on 2022-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0024_auto_20220719_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipsetdatapointsrow',
            name='datapoints',
            field=models.ManyToManyField(related_name='chipsetdatapointsrow_datapoint', to='ui.ChipsetDatapoint'),
        ),
    ]
