# Generated by Django 3.2.4 on 2022-07-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0025_alter_chipsetdatapointsrow_datapoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipsetdatapointsrow',
            name='gene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='chipsetdatapointsrow_gene', to='ui.gene'),
        ),
    ]
