# Generated by Django 3.2.4 on 2022-07-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0026_chipsetdatapointsrow_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipsetdatapointsrow',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chipsetdatapointsrow_gene', to='ui.gene'),
        ),
    ]
